name: MooCaption
author: marcelo.origoni
category: Widgets
tags: [Widgets, image caption, caption]
#docs: http://marcelo.origoni.com.ar/mooCaption/
#demo: http://marcelo.origoni.com.ar/mooCaption/demo.php
#current: 1.1.2